Fix regression in `#[derive(Insertable)]` while having the same bound with different lifetimes
This commit fixes a regression in `#[derive(Insertable)]` if the struct
contains several fields with the same type, but different lifetimes. The
most simple example for this is something like:

```rust
#[derive(Insertable)]
struct List<'a> {
	list: &'a str,
	identifier: &'static str,
}
```

The improved diagnostic code introduced in
https://github.com/diesel-rs/diesel/pull/4884 would then generate bounds
like

```
where
    &'a str: AsExpression<<lists::list as Expression>::SqlType>,
    &'static str: AsExpression<<lists::identifier as
Expression>::SqlType>,
```

which in turn results in an error like this:

```
error[E0284]: type annotations needed
  --> src/main.rs:10:10
   |
10 | #[derive(Insertable)]
   |          ^^^^^^^^^^ cannot infer type
   |
   = note: cannot satisfy `<&'a str as AsExpression<diesel::sql_types::Text>>::Expression == _`
   = note: this error originates in the derive macro `Insertable` (in Nightly builds, run with -Z macro-backtrace for more info)

error[E0283]: type annotations needed: cannot satisfy `&str: AsExpression<diesel::sql_types::Text>`
  --> src/main.rs:12:12
   |
12 | pub struct List<'a> {
   |            ^^^^^^^^^^^^^^^^^
   |
note: multiple `impl`s or `where` clauses satisfying `&str: AsExpression<diesel::sql_types::Text>` found
  --> src/main.rs:13:5
   |
10 | #[derive(Insertable)]
   |          ---------- in this derive macro expansion
...
13 |     list: &'a str,
   |     ^^^^
14 |     identifier: &'static str,
   |     ^^^^^^^^^^^
   = note: and another `impl` found in the `diesel` crate: `impl<'__expr> AsExpression<diesel::sql_types::Text> for &'__expr str;`
note: required for `CodeListEntry<'a>` to implement `diesel::Insertable<lists::table>`
  --> src/main.rs:10:10
   |
10 | #[derive(Insertable)]
   |          ^^^^^^^^^^
11 | pub struct List<'a> {
   |            ^^^^^^^^^^^^^^^^^
12 |     list: &'a str,
   |     ---- unsatisfied trait bound introduced in this `derive` macro
   = note: this error originates in the derive macro `Insertable` (in Nightly builds, run with -Z macro-backtrace for more info)
```

This is in the end caused by a bug in rustc's trait resulution:
https://github.com/rust-lang/rust/issues/21974, which might at least
partically get resolved with the new trait solver. 

Until then we just filter out bounds if they appear with different
lifetimes. This is might lead to worse diagnostics in these edge cases,
but that should be acceptable.