Allow Unused External Crates in diesel_derives
 ## Problem
With an older version of Rust(`nightly-2017-09-20-x86_64-apple-darwin`), `diesel` does not compile due to `unused
external crate` errors:
```
error: unused extern crate
  --> src/type_impls/primitives.rs:69:14
   |
69 |     #[derive(FromSqlRow)]
   |              ^^^^^^^^^^

error: unused extern crate
 --> src/type_impls/decimal.rs:9:14
  |
9 |     #[derive(FromSqlRow, AsExpression)]
  |              ^^^^^^^^^^
```

 ## Solution
Because it's a simple fix and not worth being a stopper, allow unused
extern crates and allow diesel to compile.