Impl `UndecoratedInsertRecord` for `OwnedBatchInsert`.
Attempts to resolve #1930.  Unfortunately, I can't run the unit tests
for reasons I don't fully understand, so it's not a FULL fix.  It builds
fine, but trying to do `cargo test` gives me:

```
error: At least one backend must be specified for use with this crate.
 In Cargo.toml, please specify `features = ["postgresql"]`, `features = ["mysql"]`, or `features = ["sqlite"]`

 ex. `infer_schema_internals { features = ["postgres"] }`

  --> /home/icefox/.cargo/registry/src/github.com-1ecc6299db9ec823/infer_schema_internals-1.3.0/src/inference.rs:70:14
   |
70 |           _ => compile_error!(
   |  ______________^
71 | |             "At least one backend must be specified for use with this crate.\n \
72 | |              In Cargo.toml, please specify `features = [\"postgresql\"]`, \
73 | |              `features = [\"mysql\"]`, or `features = [\"sqlite\"]`\n\n \
74 | |              ex. `infer_schema_internals { features = [\"postgres\"] }`\n "
75 | |         ),
   | |_________^

error: aborting due to previous error
```

Also, relies on #1923 or something equivalent.