Improve the error message when `insert` is called with an owned value
Prior to this commit, the error will occur when you attempt to call
`execute`, `get_result`, or `get_results`. The message will indicate
that those methods don't exist, because `InsertQuery` doesn't implement
`QueryFragment`, with a very long generic type signature. The reason for
this being that `StructName` doesn't implement `Insertable`,
`&StructName` does.

This now handles this common error as quickly and directly as possible.
The error message will now be:

```
error: mismatched types:
 expected `&_`
    found `StructName`
```

This does cause a minor change in functionality, as it becomes
impossible to pass an owned value to `insert`. I don't think this is a
problem, as really the only thing this removes is the ability to
construct an insert statement and the return the query without executing
it, e.g.:

```rust
fn build_insert_query(name: &str) -> Box<QueryFragment<Pg>> {
    let new_user = NewUser { name: name };
    insert(new_user).into(users::table)
}
```

However, this case just doesn't seem like it matters, and I'm fine with
losing support for it.

Fixes #249.